### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by romaniuk3** [romaniuk3/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Newpullg** [comment]
In 305 AC
Samwell was chosen as the new Grand Maester by Bran after his election. After his appointment, he assisted Archmaester Ebrose with the title of his history book recounting the wars in Westeros after the assassination of Robert Baratheon, which he showed to Tyrion, the new Hand of the King, at the first small council meeting.

In 303 AC
Sam reminds all of the black brothers present that Jon was Jeor Mormont's personal steward, that he led the force to deal with the mutineers at Craster's Keep, and took command of Castle Black's garrison during the wildling attack when Thorne was wounded.

In 302 AC
After the arrival of Stannis Baratheon, Sam is present when the Night's Watch burn the bodies of those who were slain during the battle.

In 300 AC
Sam assumes Jon's responsibilities as steward to the Lord Commander so that Jon can accompany Qhorin Halfhand scouting the Skirling Pass. The party does not return and are believed dead but Sam refuses to give up hope. He finds a cache of Dragonglass weapons buried at the Fist while working with Grenn and Edd.

300 AC - 303 AC
Worked in the night watch

In 283 AC
Samwell Tarly arrives at Castle Black.
